apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-rutorrent
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/rutorrent/download"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-rutorrent-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/rutorrent/config"
