apiVersion: v1
kind: Service
metadata:
  name: rutorrent
  labels:
    app: rutorrent
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 5000
      name: torrent1
      targetPort: 5000
    - port: 51413
      name: torrent2
      targetPort: 51413
    - port: 6881
      name: torrentudp
      protocol: UDP
      targetPort: 6881
  selector:
    app: rutorrent
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ru-pv-claim
  labels:
    app: rutorrent
spec:
  storageClassName: manual
  volumeName: "pv-volume-rutorrent"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ru-pv-claim-config
  labels:
    app: rutorrent
spec:
  storageClassName: manual
  volumeName: "pv-volume-rutorrent-config"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: rutorrent
  name: rutorrent
spec:
    containers:
    - image: linuxserver/rutorrent
      name: rutorrent
      env:
      - name:  TZ
        value: Europe/London
      ports:
      - containerPort: 80
      - containerPort: 5000
      - containerPort: 51413
      - containerPort: 6881
        protocol: UDP
      volumeMounts:
      - name: rutorrent-persistent-storage
        mountPath: /downloads
      - name: rutorrent-persistent-config
        mountPath: /config

    volumes:
    - name: rutorrent-persistent-storage
      persistentVolumeClaim:
        claimName: ru-pv-claim
    - name: rutorrent-persistent-config
      persistentVolumeClaim:
        claimName: ru-pv-claim-config
